#!/usr/bin/env bash

hc() {
	herbstclient "$@"
}

hc emit_hook reload

#xsetroot -solid '#5a6e3a' &
picom &
nitrogen --restore &
#xwallpaper --center /home/crispy/wallpaper2.jpg &

hc keyunbind --all

Mod=Mod4
myTerm=alacritty
myEditor="alacritty -e nvim"
myExplorer="alacritty -e ranger"
myScreenLocker="betterlockscreen -l --blur 1.0"

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $myTerm
hc keybind $Mod-e spawn $myExplorer
hc keybind $Mod-Shift-Control-l spawn $myScreenLocker
hc keybind $Mod-Shift-Control-p spawn scrot ~/screenshots/%Y-%m-%d::%H:%M:%S.png

hc keybind $Mod-p spawn dmenu_run -p run:

#hc keybind $Mod-F1 spawn pactl "list-sinks | grep -q Mute:.no && pactl set-sink-mute 0 1 || pactl set-sink-mute 0 0"
hc keybind $Mod-F2 spawn pactl -- set-sink-volume 0 -5%
hc keybind $Mod-F3 spawn pactl -- set-sink-volume 0 +5%

hc keybind $Mod-Left          focus left
hc keybind $Mod-Down          focus down
hc keybind $Mod-Up            focus up
hc keybind $Mod-Right         focus right

hc keybind $Mod-Shift-Left    shift left
hc keybind $Mod-Shift-Down    shift down
hc keybind $Mod-Shift-Up      shift up
hc keybind $Mod-Shift-Right   shift right

hc keybind $Mod-u             split  bottom  0.5
hc keybind $Mod-o             split  right   0.5
hc keybind $Mod-Control-space split explode

resizestep=0.05
hc keybind $Mod-Control-Left   resize left +$resizestep
hc keybind $Mod-Control-Down   resize down +$resizestep
hc keybind $Mod-Control-Up     resize up +$resizestep
hc keybind $Mod-Control-Right  resize right +$resizestep

tag_names=("1" "2" "3" "4" "5" "6" "7" "8" "9")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#504945'
hc set frame_border_normal_color '#32302f'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set focus_follows_mouse 1

hc attr theme.active.color '#458588'
hc attr theme.normal.color '#3c3836'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#3c3836'
hc attr theme.active.inner_color '#458588'
hc attr theme.active.outer_color '#458588'
hc attr theme.background_color '#3c3836'

hc set window_gap 5
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 1

hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

hc detect_monitors

panel=~/.config/herbstluftwm/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

