#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

sxhkd &
picom &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
~/.config/polybar/./launch.sh &

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio	0.5
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true
bspc config history_aware_focus		true

bspc config active_border_color		"#458588"
bspc config normal_border_color		"#3c3836"
bspc config focused_border_color	"#458588"
bspc config presel_border_color		"#458588"
bspc config urgent_border_color		"#fe8019"
